# Generated by Django 6.0.3 on 2026-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0003_deliveryoption_sale_delivery_charge_sale_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
