# Generated by Django 6.0.3 on 2026-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0004_medicine_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='uses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
