# Generated by Django 6.0.3 on 2026-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0006_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HealKart', max_length=255)),
                ('qr_code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('admin_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
