# Generated by Django 6.0.3 on 2026-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0007_pharmacysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacysettings',
            name='qr_code_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
