# Generated by Django 6.0.3 on 2026-04-10 03:20 - Modified to handle existing data

import django.db.models.deletion
import rx.models
from django.conf import settings
from django.db import migrations, models
import uuid


def generate_unique_order_numbers(apps, schema_editor):
    """Generate unique order numbers for all existing Sales"""
    Sale = apps.get_model('rx', 'Sale')
    for sale in Sale.objects.all():
        sale.order_number = f"ORD-{uuid.uuid4().hex[:8].upper()}"
        sale.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0008_alter_pharmacysettings_qr_code_url'),
    ]

    operations = [
        # Add order_number WITHOUT unique constraint first
        migrations.AddField(
            model_name='sale',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=20),
            preserve_default=False,
        ),
        # Populate unique order numbers for existing rows
        migrations.RunPython(generate_unique_order_numbers, migrations.RunPython.noop),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='sale',
            name='order_number',
            field=models.CharField(default=rx.models.generate_order_number, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Pickup/Delivery'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='rx.sale')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
