# Generated by Django 6.0.3 on 2026-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0009_add_order_status_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
