# Generated by Django 6.0.3 on 2026-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0011_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='estimated_days',
            field=models.IntegerField(default=1),
        ),
    ]
