# Generated by Django 6.0.3 on 2026-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0012_deliveryoption_estimated_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='base_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='per_km_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='distance_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total',
            field=models.IntegerField(),
        ),
    ]
