# Generated by Django 6.0.3 on 2026-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0013_alter_deliveryoption_base_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_screenshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('COD', 'Cash on Delivery'), ('QR', 'QR Code / Digital Wallet'), ('CARD', 'Card')], default='CASH', max_length=50),
        ),
    ]
